In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.embeddings import OpenAIEmbeddings

In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883: A NOVEL THAT READERS and critic...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982: A new 'Christie for Christmas' ...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736: A memorable, mesmerizing heroin..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897: Lewis' work on the nature of lo...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934: ""In The Problem of Pain, C.S. L..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222: On A Train Journey Home To Nort...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014: This book tells the tale of a m...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623: Wisdom to Create a Life of Pass...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535: This collection of the timeless...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059: Since the three volume edition ...

In [5]:
books["tagged_description"]

0       9780002005883: A NOVEL THAT READERS and critic...
1       9780002261982: A new 'Christie for Christmas' ...
2       9780006178736: A memorable, mesmerizing heroin...
3       9780006280897: Lewis' work on the nature of lo...
4       9780006280934: "In The Problem of Pain, C.S. L...
                              ...
5192    9788172235222: On A Train Journey Home To Nort...
5193    9788173031014: This book tells the tale of a m...
5194    9788179921623: Wisdom to Create a Life of Pass...
5195    9788185300535: This collection of the timeless...
5196    9789027712059: Since the three volume edition ...
Name: tagged_description, Length: 5197, dtype: object

In [6]:
books["tagged_description"].dropna().to_csv("tagged_description.txt", index=False, header=False)

In [8]:
# Load raw text
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()

# Split into chunks
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=100, separator="\n")
documents = text_splitter.split_documents(raw_documents)

# Create FAISS vector store
embedding = OpenAIEmbeddings()
db_books = FAISS.from_documents(documents, embedding)

Created a chunk of size 1171, which is longer than the specified 1000
Created a chunk of size 1217, which is longer than the specified 1000
Created a chunk of size 1091, which is longer than the specified 1000
Created a chunk of size 1192, which is longer than the specified 1000
Created a chunk of size 1268, which is longer than the specified 1000
Created a chunk of size 2011, which is longer than the specified 1000
Created a chunk of size 1226, which is longer than the specified 1000
Created a chunk of size 1187, which is longer than the specified 1000
Created a chunk of size 1217, which is longer than the specified 1000
Created a chunk of size 1194, which is longer than the specified 1000
Created a chunk of size 1060, which is longer than the specified 1000
Created a chunk of size 1273, which is longer than the specified 1000
Created a chunk of size 1638, which is longer than the specified 1000
Created a chunk of size 1133, which is longer than the specified 1000
Created a chunk of size 1326, which is longer than the specified 1000
Created a chunk of size 1122, which is longer than the specified 1000
Created a chunk of size 1196, which is longer than the specified 1000
Created a chunk of size 2013, which is longer than the specified 1000
Created a chunk of size 1289, which is longer than the specified 1000
Created a chunk of size 1232, which is longer than the specified 1000
Created a chunk of size 1243, which is longer than the specified 1000
Created a chunk of size 1129, which is longer than the specified 1000
Created a chunk of size 1076, which is longer than the specified 1000
Created a chunk of size 1321, which is longer than the specified 1000
Created a chunk of size 2835, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1007, which is longer than the specified 1000
Created a chunk of size 2511, which is longer than the specified 1000
Created a chunk of size 1425, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1147, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 1089, which is longer than the specified 1000
Created a chunk of size 1815, which is longer than the specified 1000
Created a chunk of size 1831, which is longer than the specified 1000
Created a chunk of size 1065, which is longer than the specified 1000
Created a chunk of size 1183, which is longer than the specified 1000
Created a chunk of size 1287, which is longer than the specified 1000
Created a chunk of size 1645, which is longer than the specified 1000
Created a chunk of size 1933, which is longer than the specified 1000
Created a chunk of size 2009, which is longer than the specified 1000
Created a chunk of size 2286, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 1145, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1089, which is longer than the specified 1000
Created a chunk of size 1484, which is longer than the specified 1000
Created a chunk of size 1138, which is longer than the specified 1000
Created a chunk of size 1035, which is longer than the specified 1000
Created a chunk of size 1018, which is longer than the specified 1000
Created a chunk of size 1091, which is longer than the specified 1000
Created a chunk of size 1915, which is longer than the specified 1000
Created a chunk of size 2617, which is longer than the specified 1000
Created a chunk of size 1581, which is longer than the specified 1000
Created a chunk of size 1531, which is longer than the specified 1000
Created a chunk of size 2033, which is longer than the specified 1000
Created a chunk of size 1620, which is longer than the specified 1000
Created a chunk of size 1192, which is longer than the specified 1000
Created a chunk of size 1285, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 1278, which is longer than the specified 1000
Created a chunk of size 1059, which is longer than the specified 1000
Created a chunk of size 1164, which is longer than the specified 1000
Created a chunk of size 1059, which is longer than the specified 1000
Created a chunk of size 1085, which is longer than the specified 1000
Created a chunk of size 2763, which is longer than the specified 1000
Created a chunk of size 1036, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1067, which is longer than the specified 1000
Created a chunk of size 1227, which is longer than the specified 1000
Created a chunk of size 1808, which is longer than the specified 1000
Created a chunk of size 1018, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 1772, which is longer than the specified 1000
Created a chunk of size 1271, which is longer than the specified 1000
Created a chunk of size 1020, which is longer than the specified 1000
Created a chunk of size 1180, which is longer than the specified 1000
Created a chunk of size 1718, which is longer than the specified 1000
Created a chunk of size 1682, which is longer than the specified 1000
Created a chunk of size 1131, which is longer than the specified 1000
Created a chunk of size 2006, which is longer than the specified 1000
Created a chunk of size 1174, which is longer than the specified 1000
Created a chunk of size 2142, which is longer than the specified 1000
Created a chunk of size 1323, which is longer than the specified 1000
Created a chunk of size 1115, which is longer than the specified 1000
Created a chunk of size 1319, which is longer than the specified 1000
Created a chunk of size 1124, which is longer than the specified 1000
Created a chunk of size 1021, which is longer than the specified 1000
Created a chunk of size 1010, which is longer than the specified 1000
Created a chunk of size 1060, which is longer than the specified 1000
Created a chunk of size 1256, which is longer than the specified 1000
Created a chunk of size 1101, which is longer than the specified 1000
Created a chunk of size 1146, which is longer than the specified 1000
Created a chunk of size 1553, which is longer than the specified 1000
Created a chunk of size 1655, which is longer than the specified 1000
Created a chunk of size 1498, which is longer than the specified 1000
Created a chunk of size 1280, which is longer than the specified 1000
Created a chunk of size 1049, which is longer than the specified 1000
Created a chunk of size 1669, which is longer than the specified 1000
Created a chunk of size 1619, which is longer than the specified 1000
Created a chunk of size 1098, which is longer than the specified 1000
Created a chunk of size 1600, which is longer than the specified 1000
Created a chunk of size 1963, which is longer than the specified 1000
Created a chunk of size 1711, which is longer than the specified 1000
Created a chunk of size 1950, which is longer than the specified 1000
Created a chunk of size 1028, which is longer than the specified 1000
Created a chunk of size 1810, which is longer than the specified 1000
Created a chunk of size 1521, which is longer than the specified 1000
Created a chunk of size 1090, which is longer than the specified 1000
Created a chunk of size 1096, which is longer than the specified 1000
Created a chunk of size 1168, which is longer than the specified 1000
Created a chunk of size 1262, which is longer than the specified 1000
Created a chunk of size 1483, which is longer than the specified 1000
Created a chunk of size 1040, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1446, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 1147, which is longer than the specified 1000
Created a chunk of size 1372, which is longer than the specified 1000
Created a chunk of size 1625, which is longer than the specified 1000
Created a chunk of size 1168, which is longer than the specified 1000
Created a chunk of size 1179, which is longer than the specified 1000
Created a chunk of size 1182, which is longer than the specified 1000
Created a chunk of size 1001, which is longer than the specified 1000
Created a chunk of size 1012, which is longer than the specified 1000
Created a chunk of size 1025, which is longer than the specified 1000
Created a chunk of size 1360, which is longer than the specified 1000
Created a chunk of size 1175, which is longer than the specified 1000
Created a chunk of size 1397, which is longer than the specified 1000
Created a chunk of size 1219, which is longer than the specified 1000
Created a chunk of size 2210, which is longer than the specified 1000
Created a chunk of size 1374, which is longer than the specified 1000
Created a chunk of size 2878, which is longer than the specified 1000
Created a chunk of size 1280, which is longer than the specified 1000
Created a chunk of size 1715, which is longer than the specified 1000
Created a chunk of size 1641, which is longer than the specified 1000
Created a chunk of size 2401, which is longer than the specified 1000
Created a chunk of size 2123, which is longer than the specified 1000
Created a chunk of size 1491, which is longer than the specified 1000
Created a chunk of size 1694, which is longer than the specified 1000
Created a chunk of size 1421, which is longer than the specified 1000
Created a chunk of size 1174, which is longer than the specified 1000
Created a chunk of size 1360, which is longer than the specified 1000
Created a chunk of size 2182, which is longer than the specified 1000
Created a chunk of size 1096, which is longer than the specified 1000
Created a chunk of size 2172, which is longer than the specified 1000
Created a chunk of size 1457, which is longer than the specified 1000
Created a chunk of size 1457, which is longer than the specified 1000
Created a chunk of size 1976, which is longer than the specified 1000
Created a chunk of size 1988, which is longer than the specified 1000
Created a chunk of size 1649, which is longer than the specified 1000
Created a chunk of size 2724, which is longer than the specified 1000
Created a chunk of size 1635, which is longer than the specified 1000
Created a chunk of size 1287, which is longer than the specified 1000
Created a chunk of size 1485, which is longer than the specified 1000
Created a chunk of size 1052, which is longer than the specified 1000
Created a chunk of size 1006, which is longer than the specified 1000
Created a chunk of size 1153, which is longer than the specified 1000
Created a chunk of size 1217, which is longer than the specified 1000
Created a chunk of size 1033, which is longer than the specified 1000
Created a chunk of size 2457, which is longer than the specified 1000
Created a chunk of size 1350, which is longer than the specified 1000
Created a chunk of size 1272, which is longer than the specified 1000
Created a chunk of size 1120, which is longer than the specified 1000
Created a chunk of size 1549, which is longer than the specified 1000
Created a chunk of size 1202, which is longer than the specified 1000
Created a chunk of size 1163, which is longer than the specified 1000
Created a chunk of size 1150, which is longer than the specified 1000
Created a chunk of size 1025, which is longer than the specified 1000
Created a chunk of size 1777, which is longer than the specified 1000
Created a chunk of size 1166, which is longer than the specified 1000
Created a chunk of size 1012, which is longer than the specified 1000
Created a chunk of size 1020, which is longer than the specified 1000
Created a chunk of size 1326, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1126, which is longer than the specified 1000
Created a chunk of size 1599, which is longer than the specified 1000
Created a chunk of size 1964, which is longer than the specified 1000
Created a chunk of size 2451, which is longer than the specified 1000
Created a chunk of size 1799, which is longer than the specified 1000
Created a chunk of size 1569, which is longer than the specified 1000
Created a chunk of size 1222, which is longer than the specified 1000
Created a chunk of size 1383, which is longer than the specified 1000
Created a chunk of size 1453, which is longer than the specified 1000
Created a chunk of size 1105, which is longer than the specified 1000
Created a chunk of size 1301, which is longer than the specified 1000
Created a chunk of size 1764, which is longer than the specified 1000
Created a chunk of size 1007, which is longer than the specified 1000
Created a chunk of size 1025, which is longer than the specified 1000
Created a chunk of size 1067, which is longer than the specified 1000
Created a chunk of size 1012, which is longer than the specified 1000
Created a chunk of size 1065, which is longer than the specified 1000
Created a chunk of size 1630, which is longer than the specified 1000
Created a chunk of size 1594, which is longer than the specified 1000
Created a chunk of size 1588, which is longer than the specified 1000
Created a chunk of size 1262, which is longer than the specified 1000
Created a chunk of size 1131, which is longer than the specified 1000
Created a chunk of size 1106, which is longer than the specified 1000
Created a chunk of size 1081, which is longer than the specified 1000
Created a chunk of size 1534, which is longer than the specified 1000
Created a chunk of size 1205, which is longer than the specified 1000
Created a chunk of size 1096, which is longer than the specified 1000
Created a chunk of size 1250, which is longer than the specified 1000
Created a chunk of size 1057, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1014, which is longer than the specified 1000
Created a chunk of size 1355, which is longer than the specified 1000
Created a chunk of size 1415, which is longer than the specified 1000
Created a chunk of size 1026, which is longer than the specified 1000
Created a chunk of size 1219, which is longer than the specified 1000
Created a chunk of size 1134, which is longer than the specified 1000
Created a chunk of size 1198, which is longer than the specified 1000
Created a chunk of size 1894, which is longer than the specified 1000
Created a chunk of size 3171, which is longer than the specified 1000
Created a chunk of size 1535, which is longer than the specified 1000
Created a chunk of size 1591, which is longer than the specified 1000
Created a chunk of size 1610, which is longer than the specified 1000
Created a chunk of size 1626, which is longer than the specified 1000
Created a chunk of size 1422, which is longer than the specified 1000
Created a chunk of size 1117, which is longer than the specified 1000
Created a chunk of size 1131, which is longer than the specified 1000
Created a chunk of size 1039, which is longer than the specified 1000
Created a chunk of size 1142, which is longer than the specified 1000
Created a chunk of size 1181, which is longer than the specified 1000
Created a chunk of size 1051, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1170, which is longer than the specified 1000
Created a chunk of size 2035, which is longer than the specified 1000
Created a chunk of size 1118, which is longer than the specified 1000
Created a chunk of size 1439, which is longer than the specified 1000
Created a chunk of size 1114, which is longer than the specified 1000
Created a chunk of size 1065, which is longer than the specified 1000
Created a chunk of size 1472, which is longer than the specified 1000
Created a chunk of size 1437, which is longer than the specified 1000
Created a chunk of size 1331, which is longer than the specified 1000
Created a chunk of size 1722, which is longer than the specified 1000
Created a chunk of size 1531, which is longer than the specified 1000
Created a chunk of size 1652, which is longer than the specified 1000
Created a chunk of size 1582, which is longer than the specified 1000
Created a chunk of size 1647, which is longer than the specified 1000
Created a chunk of size 1690, which is longer than the specified 1000
Created a chunk of size 2034, which is longer than the specified 1000
Created a chunk of size 1110, which is longer than the specified 1000
Created a chunk of size 1050, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1092, which is longer than the specified 1000
Created a chunk of size 1104, which is longer than the specified 1000
Created a chunk of size 1131, which is longer than the specified 1000
Created a chunk of size 1341, which is longer than the specified 1000
Created a chunk of size 1083, which is longer than the specified 1000
Created a chunk of size 1166, which is longer than the specified 1000
Created a chunk of size 1006, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 1229, which is longer than the specified 1000
Created a chunk of size 1238, which is longer than the specified 1000
Created a chunk of size 2943, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1493, which is longer than the specified 1000
Created a chunk of size 1160, which is longer than the specified 1000
Created a chunk of size 1211, which is longer than the specified 1000
Created a chunk of size 1490, which is longer than the specified 1000
Created a chunk of size 1087, which is longer than the specified 1000
Created a chunk of size 1803, which is longer than the specified 1000
Created a chunk of size 1598, which is longer than the specified 1000
Created a chunk of size 1031, which is longer than the specified 1000
Created a chunk of size 1362, which is longer than the specified 1000
Created a chunk of size 1644, which is longer than the specified 1000
Created a chunk of size 1383, which is longer than the specified 1000
Created a chunk of size 1766, which is longer than the specified 1000
Created a chunk of size 1974, which is longer than the specified 1000
Created a chunk of size 1241, which is longer than the specified 1000
Created a chunk of size 1120, which is longer than the specified 1000
Created a chunk of size 1052, which is longer than the specified 1000
Created a chunk of size 1007, which is longer than the specified 1000
Created a chunk of size 1122, which is longer than the specified 1000
Created a chunk of size 1130, which is longer than the specified 1000
Created a chunk of size 1038, which is longer than the specified 1000
Created a chunk of size 1283, which is longer than the specified 1000
Created a chunk of size 1476, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 1220, which is longer than the specified 1000
Created a chunk of size 1006, which is longer than the specified 1000
Created a chunk of size 1046, which is longer than the specified 1000

In [9]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883: A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [10]:
db_books = Chroma.from_documents(documents, embedding=OpenAIEmbeddings())

In [11]:
query="A book to teach children about nature"
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='029dc8e3-f433-40e1-bf94-31e55c1c2655', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069: Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."\n"9780786808373: Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='ac216bb3-87d2-4b02-81f5-7defaef73577', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380: Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."\n"9780786808397: Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='4930a159-81c8-4e1f-b072-2c121df5a3da', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208: First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(id='eedcef2e-29dd-48c0-810f-9a5de57bca8a', metadata={'source': 'tagged_description.txt'}, page_content='"9780374299194: The author describes growing up in a family of all boys in Webster Groves, Missouri, reflecting on such topics as the dynamics of a Christian youth fellowship, his role as the school prankster, his marriage, and the life lessons he has learned from birds."\n"9780374422080: This Newbery Honor Book tells the story of 11 -year-old Primrose, who lives in a small fishing village in British Columbia. She recounts her experiences and all she learns about human nature and the unpredictability of life after her parents are lost at sea."'),
 Document(id='5848f93d-ba8b-4239-bd0a-ac06ecff2ab5', metadata={'source': 'tagged_description.txt'}, page_content='"9780941807555: THE LITTLE BIG BOOK FOR GOD\'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God\'s enduring message of love, GOD\'S CHILDREN is sure to provide an endless wellspring of inspiration and hope."'),
 Document(id='50b62c24-741a-4576-969d-b56fedf408c4', metadata={'source': 'tagged_description.txt'}, page_content='"9780006646006: Joe and his parents are enjoying a summer holiday by the sea at the Ocean Star Hotel. The sky is bright blue, the sun shines and Joe loves all that the seaside has to offer. But when the fog rolls in and rain falls Joe begins to wish that he was back at home again. Things change, however, when the owner of the hotel invites Joe to share in a magical world, only a few steps away. The loft is black as night but then above Joe\'s head a thousand tiny stars begin to sparkle and in the distance he hears the chug-chug-chug of a model train. A whole world is soon to open up before Joe\'s eyes, a world of snow-capped mountains, great deserts, and rocking fishing boats."\n"9780007105045: ""The two works \'On fairy-stories\' and \'Leaf by Niggle\' were first brought together to form the book \'Tree and leaf\' in 1964. In this new edition a third element is added: the poem Mythopoeia, the making of myths...""--Preface."'),
 Document(id='76144803-bbde-4fb2-be5c-e7ab2be40671', metadata={'source': 'tagged_description.txt'}, page_content='"9780451456816: A collection of stories that detail modern science\'s effect on humankind\'s notions of conception, birth, and parenting includes contributions from Michael Armstrong, Robert Silverberg, Susan Palwick, and others"\n"9780451457592: Fifteen-year-old Ariella spends her days in the forest caring for the animals, but when her father dies and she is threatened with marriage to a cousin she has never seen, a remarkable horselike creature from the woods will reward the girl\'s compassion with a special gift."\n"9780451461636: After Weather Warden Joanne Baldwin prevents Mother Earth from destroying the planet, she struggles to recover her identity after losing her memories at the hands of a vengeful jinn."\n9780451527400: The oldest extant poem in a modern European language chronicles a feudal newly Christianized world still populated by the monsters and demons of the ancient world. Reprint.'),
 Document(id='3ab57794-b19e-4faa-93cf-9b08f4ed471b', metadata={'source': 'tagged_description.txt'}, page_content='"9780786818723: Violet, a very curious young mouse, invites babies and toddlers into her home to explore, room by room, her favorite things. Delightfully written rhythmic verse and engaging illustrations lead children to discover the feel of objects that surround them in their everyday world. From touching Violet\'s fluffy poodle to joining her as she puts sticky toothpaste on her brush, children will want to visit Violet\'s House time and time again."\n"9780786819119: Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub."\n"9780786838943: Eleven-year-old Oliver, an American boy residing in Paris, discovers, much to his astonishment, that phantoms live within the windowpanes and have selected Oliver to lead a war against the ""soul-stealers"" that inhabit mirrors."'),
 Document(id='1efda950-0b20-4d84-8803-8958f76b001b', metadata={'source': 'tagged_description.txt'}, page_content='"9780764122781: Titles in this series present basic information on reptiles plus specific instructions for their care. Each book opens with a description of the animal as it exists in its natural habitat, then continues with information on its life cycle and distribution in nature. Readers then get advice on selecting a good specimen, determining sex, and providing proper housing, feeding, and health care. Books are heavily illustrated with instructive color photos."\n"9780764134289: (back cover) ALL THE ESSENTIALS IN ONE CLEAR VOLUME by David A. Stewart, Ed. D., Elizabeth Stewart, and Jessalyn Little, M. Ed. A clear and easy approach to learning American Sign Language Updated to cover vocabulary related to new technological developments More than 800 illustrative line drawings How to use facial grammar to supplement manual signing How to combine words to express complete statements"'),
 Document(id='8d89017c-35ff-445a-9072-0d77b3b17ec7', metadata={'source': 'tagged_description.txt'}, page_content='"9780689823824: Here is a delightful look at childhood, written by master poet and storyteller Robert Louis Stevenson. In this collection of sixty-six poems, Stevenson recalls the joys of his childhood, from sailing boats down a river, to waiting for the lamplighter, to sailing off to foreign lands in his imagination. Tasha Tudor\'s watercolor paintings evoke a simpler time in the past, and celebrate two of the things she loves most -- children and nature. Her talents are the perfect match for these inspiring poems, making this a handsome gift edition that will be cherished by families for generations."')]

In [14]:
isbn_raw = docs[0].page_content.split()[0].strip()  # e.g., '"9780786808069:'
isbn_clean = isbn_raw.strip('":')  # remove leading/trailing quotes or colons
isbn = int(isbn_clean)  # safe to convert now

result = books[books["isbn13"] == isbn]
print(result)

             isbn13      isbn10                                title  \
3747  9780786808069  0786808063  Baby Einstein: Neighborhood Animals

                                authors        categories  \
3747  Marilyn Singer;Julie Aigner-Clark  Juvenile Fiction

                                              thumbnail  \
3747  http://books.google.com/books/content?id=X9a4P...

                                            description  published_year  \
3747  Children will discover the exciting world of t...          2001.0

      average_rating  num_pages  ratings_count  \
3747            3.89       16.0          180.0

                       title_and_subtitle  \
3747  Baby Einstein: Neighborhood Animals

                                     tagged_description
3747  9780786808069: Children will discover the exci...

In [17]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)
    books_list = []

    for i in range(len(recs)):
        isbn_raw = recs[i].page_content.strip('"').split()[0]
        isbn_clean = isbn_raw.strip(":")
        books_list.append(int(isbn_clean))

    return books[books["isbn13"].isin(books_list)]

In [18]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006: Joe and his parents are enjoyin...
111,9780060504083,0060504080,Small Wonder,Barbara Kingsolver,Literary Collections,http://books.google.com/books/content?id=2mrrl...,"In her new essay collection, the beloved autho...",2003.0,4.01,264.0,8738.0,Small Wonder: Essays,"9780060504083: In her new essay collection, th..."
223,9780060775858,0060775858,Goodnight Moon 60th Anniversary Edition,Margaret Wise Brown,Juvenile Fiction,http://books.google.com/books/content?id=lLYOr...,"In a great green room, tucked away in bed, is ...",2005.0,4.27,32.0,264013.0,Goodnight Moon 60th Anniversary Edition,"9780060775858: In a great green room, tucked a..."
260,9780060852559,0060852550,"Animal, Vegetable, Miracle",Barbara Kingsolver;Camille Kingsolver;Steven L...,Biography & Autobiography,http://books.google.com/books/content?id=qLkEY...,Bestselling author Barbara Kingsolver returns ...,2007.0,4.04,370.0,86130.0,"Animal, Vegetable, Miracle: A Year of Food Life",9780060852559: Bestselling author Barbara King...
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,Prodigal Summer: A Novel,9780060959036: Barbara Kingsolver's fifth nove...
399,9780062516374,006251637X,Rainforest Home Remedies,Rosita Arvigo;Nadine Epstein,Health & Fitness,http://books.google.com/books/content?id=DLnwO...,Rainforest Healing from Your Home and Garden F...,2001.0,4.12,221.0,65.0,Rainforest Home Remedies: The Maya Way To Heal...,9780062516374: Rainforest Healing from Your Ho...
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,"R-T, Margaret, and the Rats of NIMH",9780064403870: When Margaret and her younger b...
413,9780064405850,0064405850,Strawberry Girl 60th Anniversary Edition,Lois Lenski,Juvenile Fiction,http://books.google.com/books/content?id=AQXM2...,"The land was theirs, but so were its hardships...",1995.0,3.86,208.0,10655.0,Strawberry Girl 60th Anniversary Edition,"9780064405850: The land was theirs, but so wer..."
424,9780064410724,0064410722,Four Stupid Cupids,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=471OU...,The students' scheme to find a love match for ...,2001.0,3.52,224.0,110.0,Four Stupid Cupids,9780064410724: The students' scheme to find a ...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208: First published more than three...
879,9780152045739,0152045732,The Little Red Lighthouse and the Great Gray B...,Hildegarde Hoyt Swift;Lynd Ward,Juvenile Fiction,http://books.google.com/books/content?id=_bJOv...,A little lighthouse on the Hudson River regain...,2003.0,4.26,64.0,2216.0,The Little Red Lighthouse and the Great Gray B...,9780152045739: A little lighthouse on the Huds...
1074,9780237525378,0237525372,Oliver Twist,Pauline Francis;Charles Dickens,Juvenile Nonfiction,http://books.google.com/books/content?id=X6RvT...,This wonderful series is a quick way into a ra...,2003.0,3.66,48.0,92.0,Oliver Twist,9780237525378: This wonderful series is a quic...
1077,9780240806082,0240806085,Directing the Documentary,Michael Rabiger,Performing Arts,http://books.google.com/books/content?id=uoKli...,Michael Rabiger guides the reader through the ...,2004.0,4.23,648.0,173.0,Directing the Documentary,9780240806082: Michael Rabiger guides the read...
1479,9780345434906,0345434900,The Real James Herriot,James Wight;Jim Wight,Biography & Autobiography,http://books.google.com/books/content?id=TrOoi...,A portrait of the best-selling author of All C...,2001.0,4.20,371.0,4178.0,The Real James Herriot: A Memoir of My Father,9780345434906: A portrait of the best-selling ...
1638,9780374299194,0374299196,The Discomfort Zone,Jonathan Franzen,Biography & Autobiography,http://books.google.com/books/content?id=Z2vOA...,The author describes growing up in a family of...,2006.0,3.39,195.0,4660.0,The Discomfort Zone: A Personal History,9780374299194: The author describes growing up...
1641,9780374517885,0374517886,Sammlung,Isaac Bashevis Singer,Fiction,http://books.google.com/books/content?id=B0_ws...,The Noble laureate has selected nearly 150 of ...,1982.0,4.37,624.0,1603.0,Sammlung,9780374517885: The Noble laureate has selected...
1696,9780375713934,037571393X,John James Audubon,Richard Rhodes,Art,http://books.google.com/books/content?id=4j2FD...,A biography of artist John James Audubon offer...,2006.0,4.14,528.0,437.0,John James Audubon: The Making of an American,9780375713934: A biography of artist John Jame...
1738,9780375806704,0375806709,The Phantom Tollbooth,Norton Juster,Fantasy fiction,http://books.google.com/books/content?id=BZ2pP...,"For Milo, everything's a bore. When a tollboot...",2000.0,4.21,256.0,866.0,The Phantom Tollbooth,"9780375806704: For Milo, everything's a bore. ..."
1905,9780393311037,0393311031,Hen's Teeth and Horse's Toes,Stephen Jay Gould,Nature,http://books.google.com/books/content?id=EPh9j...,A collection of essays answers questions about...,1994.0,4.10,416.0,1680.0,Hen's Teeth and Horse's Toes,9780393311037: A collection of essays answers ...
2261,9780446518628,044651862X,The Celestine Prophecy,James Redfield,Fiction,http://books.google.com/books/content?id=UXolx...,You have never read a book like this before --...,1994.0,3.63,247.0,1280.0,The Celestine Prophecy: An Adventure,9780446518628: You have never read a book like...
2301,9780446677493,0446677493,Hope is the Thing with Feathers,Christopher Cokinos,Nature,http://books.google.com/books/content?id=y7Rmu...,Presents the histories of six extinct North Am...,2001.0,4.21,384.0,294.0,Hope is the Thing with Feathers: A Personal Ch...,9780446677493: Presents the histories of six e...
2409,9780451456816,0451456815,Not of Woman Born,Constance Ash;Robert A. Silverberg,Fiction,http://books.google.com/books/content?id=nOEIA...,A collection of stories that detail modern sci...,1999.0,3.80,288.0,59.0,Not of Woman Born,9780451456816: A collection of stories that de...
2477,9780471265184,0471265187,Astronomy,Dinah L. Moché,Science,http://books.google.com/books/content?id=vBFuF...,"""A lively, up-to-date account of the basic pri...",2004.0,3.89,343.0,109.0,Astronomy: A Self-Teaching Guide,"9780471265184: ""A lively, up-to-date account o..."
2497,9780486256429,0486256421,Galapagos,William Beebe,Nature,http://books.google.com/books/content?id=wFKrG...,More than 100 splendid illustrations enhance t...,1988.0,3.84,528.0,31.0,Galapagos: World's End,9780486256429: More than 100 splendid illustra...
2503,9780486276809,0486276805,The Secret Garden Coloring Book,Frances Hodgson Burnett,Juvenile Nonfiction,http://books.google.com/books/content?id=sxHdA...,Ten-year-old Mary comes to live in a lonely ho...,2014.0,4.25,48.0,4.0,The Secret Garden Coloring Book,9780486276809: Ten-year-old Mary comes to live...
2858,9780590032490,0590032496,The witches,Roald Dahl,Juvenile Nonfiction,http://books.google.com/books/content?id=tpQxo...,"A young boy and his Norwegian grandmother, who...",1997.0,4.17,208.0,254867.0,The witches,9780590032490: A young boy and his Norwegian g...
2897,9780618111206,0618111204,Once a Wolf,Stephen R. Swinburne;Jim Brandenburg,Juvenile Nonfiction,http://books.google.com/books/content?id=UkZWu...,With powerful and rare photos by a former phot...,2001.0,4.06,48.0,42.0,Once a Wolf: How Wildlife Biologists Fought to...,9780618111206: With powerful and rare photos b...
3000,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJ...,"With more than half a million copies in print,...",1986.0,4.15,395.0,2083.0,Teach Your Child to Read in 100 Easy Lessons,9780671631987: With more than half a million c...
3197,9780689707490,0689707495,Cloudy With a Chance of Meatballs,Judi Barrett,Juvenile Fiction,http://books.google.com/books/content?id=fQU6U...,"The beloved, bestselling tale of edible weathe...",1982.0,4.16,32.0,114747.0,Cloudy With a Chance of Meatballs,"9780689707490: The beloved, bestselling tale o..."
3201,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,A Child's Garden of Verses,9780689823824: Here is a delightful look at ch...
3213,9780689860072,0689860072,Dragonsinger,Anne McCaffrey,Juvenile Fiction,http://books.google.com/books/content?id=IiLlZ...,"Menolly flees her home, because she is not per...",2003.0,4.28,288.0,34207.0,Dragonsinger,"9780689860072: Menolly flees her home, because..."
3317,9780743243780,0743243781,Teacher Man,Frank McCourt,Biography & Autobiography,http://books.google.com/books/content?id=Yhgcw...,The author describes his coming of age as a te...,2006.0,3.75,272.0,25726.0,Teacher Man: A Memoir,9780743243780: The author describes his coming...
3470,9780747566755,0747566755,The Story of Mr Sommer,Patrick Süskind;Michael Hofmann,Fiction,http://books.google.com/books/content?id=jD4hH...,A boy's village childhood with all the traditi...,2003.0,3.85,128.0,1974.0,The Story of Mr Sommer,9780747566755: A boy's village childhood with ...
3576,9780762408283,0762408286,The Mini Zen Gardening Kit,Abd Al-Hayy Moore,Gardening,http://books.google.com/books/content?id=YoZFA...,This carry-along version of our enormously pop...,2000.0,3.21,40.0,13.0,The Mini Zen Gardening Kit,9780762408283: This carry-along version of our...
3582,9780763621643,0763621641,Castle Diary,Richard Platt;Chris Riddell,Juvenile Fiction,http://books.google.com/books/content?id=rFUBA...,As a page in his uncle's castle in thirteenth-...,2003.0,3.84,128.0,1072.0,Castle Diary: The Journal of Tobias Burgess,9780763621643: As a page in his uncle's castle...
3591,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781: Titles in this series present b...
3604,9780764584657,0764584650,Astronomy For Dummies,Stephen P. Maran,Science,http://books.google.com/books/content?id=iH4Fn...,A beginner's guide to astronomy features infor...,2005.0,3.83,318.0,271.0,Astronomy For Dummies,9780764584657: A beginner's guide to astronomy...
3676,9780767908184,076790818X,A Short History of Nearly Everything,Bill Bryson,Science,http://books.google.com/books/content?id=YjAnf...,The author of A Walk in the Woods traces the B...,2004.0,4.20,544.0,228522.0,A Short History of Nearly Everything,9780767908184: The author of A Walk in the Woo...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069: Children will discover the exci...
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380: Introduce your babies to birds,..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717: A very special puddle sets Viol...
3764,9780786818723,0786818727,Baby Einstein: Violet's House,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=bC4HA...,"Violet, a very curious young mouse, invites ba...",2003.0,3.98,10.0,39.0,Baby Einstein: Violet's House: A Giant Touch-a...,"9780786818723: Violet, a very curious young mo..."
3767,9780786849734,0786849738,Disney's Little Einsteins: Galactic Goodnight,Susan Ring,Juvenile Fiction,http://books.google.com/books/content?id=Nm3N3...,"The Little Einsteins, equipped with their came...",2006.0,4.50,20.0,10.0,Disney's Little Einsteins: Galactic Goodnight,"9780786849734: The Little Einsteins, equipped ..."
4185,9780878937202,087893720X,Essentials of Conservation Biology,Richard B. Primack,Science,http://books.google.com/books/content?id=spaGQ...,Essentials of Conservation Biology (Fourth Edi...,2006.0,3.89,585.0,36.0,Essentials of Conservation Biology,9780878937202: Essentials of Conservation Biol...
4231,9780898599596,0898599598,The Ecological Approach to Visual Perception,James Jerome Gibson,Psychology,http://books.google.com/books/content?id=DrhCC...,This is a book about how we see: the environme...,1986.0,4.28,348.0,122.0,The Ecological Approach to Visual Perception,9780898599596: This is a book about how we see...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,The Little Big Book for God's Children,9780941807555: THE LITTLE BIG BOOK FOR GOD'S C...
4331,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,218.0,Providence of a Sparrow: Lessons from a Life G...,9781400033850: Describes the influence of a fo...
4455,9781405201711,1405201711,The Faraway Tree Stories,Enid Blyton,"Children's stories, English",http://books.google.com/books/content?id=2d93O...,"Jo, Bessie and Fanny move to the country and f...",1987.0,4.29,583.0,12286.0,The Faraway Tree Stories,"9781405201711: Jo, Bessie and Fanny move to th..."
4809,9781586857721,158685772X,It's Easy Being Green,Crissy Trask,House & Home,http://books.google.com/books/content?id=82_En...,Provides a comprehensive guide to adopting gre...,2006.0,3.53,168.0,326.0,It's Easy Being Green: A Handbook for Earth-fr...,9781586857721: Provides a comprehensive guide ...
5120,9781895176407,1895176409,"Galapagos, a Natural History",Michael Hume Jackson,History,http://books.google.com/books/content?id=NXS8c...,This book details the natural history of the p...,1993.0,3.87,336.0,93.0,"Galapagos, a Natural History",9781895176407: This book details the natural h...